import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Image from 'next/image';
import { useSelector } from 'react-redux';
import { FaCloudUploadAlt } from 'react-icons/fa';
import { useEffect, useState } from 'react';
import cls from'classnames';


export default function Home() {

  const userAddress = useSelector((state) => state.user.address);
  const [frontalImage, setFrontalImage] = useState(null);
  const [backImage, setBackImage] = useState(null);
  const [firmaImage, setFirmaImage] = useState(null);

  const frontalImageHandler = (e) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (reader.readyState === 2) {
        setFrontalImage(reader.result);
      }
    }
    reader.readAsDataURL(e.target.files[0]);
  }

  const backImageHandler = (e) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (reader.readyState === 2) {
        setBackImage(reader.result);
      }
    }
    reader.readAsDataURL(e.target.files[0]);
  }

  const firmaImageHandler = (e) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (reader.readyState === 2) {
        setFirmaImage(reader.result);
      }
    }
    reader.readAsDataURL(e.target.files[0]);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Vertical</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span>your address is: { userAddress ? userAddress : 'none' }</span>
        <section className={styles.formContainer}>
          <span className={styles.title}>Crear certificado de arte</span>
          <form>
            <div className={styles.formBlock}>
              <label htmlFor='autor'>Autor</label>
              <input type='text' id='autor' name='autor'/>
            </div>
            <div className={styles.formBlock}>
              <label htmlFor='titulo'>Titulo</label>
              <input type='text' id='titulo' name='titulo'/>
            </div>
            <div className={styles.formPair}>
              <div className={cls(styles.doubleItem, styles.formBlock)}>
                <label htmlFor='lugar'>Lugar</label>
                <input type='text' id='lugar' name='lugar'/>
              </div>
              <div className={cls(styles.doubleItem, styles.formBlock)}>
                <label htmlFor='year'>Año</label>
                <input type='text' id='year' name='year'/>
              </div>
            </div>
            <div className={styles.dimensiones}>
              <div className={styles.subtitleContainer}>
                <span className={styles.subtitle}>Dimensiones</span>
              </div>
              <div className={styles.formTriple}>
                <div className={cls(styles.tripleItem, styles.formBlock)}>
                  <label htmlFor='ancho'>Ancho</label>
                  <input type='text' id='ancho' name='ancho'/>
                </div>
                <div className={cls(styles.tripleItem, styles.formBlock)}>
                  <label htmlFor='largo'>Largo</label>
                  <input type='text' id='largo' name='largo'/>
                </div>
                <div className={cls(styles.tripleItem, styles.formBlock)}>
                  <label htmlFor='unidades'>Unidades</label>
                  <select id="unidades" name="unidades">
                    <option value="centímetros">centímetros</option>
                    <option value="pulgadas">pulgadas</option>
                  </select>
                </div>
              </div>
            </div>
            <div className={styles.formBlock}>
              <label htmlFor='coleccion'>Coleccion/serie</label>
              <input type='text' id='coleccion' name='coleccion'/>
            </div>
            <div className={styles.formPair}>
              <div className={cls(styles.doubleItem, styles.formBlock)}>
                <label htmlFor='categoria'>Categoria</label>
                <input type='text' id='categoria' name='categoria'/>
              </div>
              <div className={cls(styles.doubleItem, styles.formBlock)}>
                <label htmlFor='inscripcion'>Inscripcion</label>
                <input type='text' id='inscripcion' name='inscripcion'/>
              </div>
            </div>
            <div className={styles.formPair}>
              <div className={cls(styles.doubleItem, styles.formBlock)}>
                <label htmlFor='tecnicaysoporte'>Tecnica y soporte</label>
                <input type='text' id='tecnicaysoporte' name='tecnicaysoporte'/>
              </div>
              <div className={cls(styles.doubleItem, styles.formBlock)}>
                <label htmlFor='estado'>Estado de conservacion</label>
                <input type='text' id='estado' name='estado'/>
              </div>
            </div>
            <div className={styles.formBlock}>
              <label htmlFor='notas'>Notas</label>
              <textarea className={styles.textarea} id='notas' maxlength='300' rows='10'></textarea>
            </div>
            <div className={styles.imageContainer}>
              <div className={styles.imageContainerTitle}>
                <span>Vista Frontal</span>
              </div>
              <div className={styles.imageSection}>
                {
                  frontalImage
                  ?
                  <div className={styles.image}>
                    <Image alt='' src={frontalImage} layout='responsive' objectFit='cover' height={150} width={200}/>
                  </div>
                  :
                  <>
                    <FaCloudUploadAlt className={styles.icon} />
                    <span>No se ha seleccionado un archivo</span>
                  </>
                }
              </div>
              {
                frontalImage
                ?
                <button onClick={() => setFrontalImage(null)}>Remover</button>
                :
                <input id='defaultFrontalBtn' type='file' accept='image/*' onChange={frontalImageHandler} />
              }
            </div>
            <div className={styles.imageContainer}>
              <div className={styles.imageContainerTitle}>
                <span>Vista Trasera</span>
              </div>
              <div className={styles.imageSection}>
              {
                  backImage
                  ?
                  <div className={styles.image}>
                    <Image alt='' src={backImage} layout='responsive' objectFit='cover' height={150} width={200}/>
                  </div>
                  :
                  <>
                    <FaCloudUploadAlt className={styles.icon} />
                    <span>No se ha seleccionado un archivo</span>
                  </>
                }
              </div>
              {
                backImage
                ?
                <button onClick={() => setBackImage(null)}>Remover</button>
                :
                <input id='defaultFrontalBtn' type='file' accept='image/*' onChange={frontalImageHandler} />
              }
            </div>
            <div className={styles.imageContainer}>
              <div className={styles.imageContainerTitle}>
                <span>Inscripcion</span>
              </div>
              <div className={styles.imageSection}>
              {
                  firmaImage
                  ?
                  <div className={styles.image}>
                    <Image alt='' src={firmaImage} layout='responsive' objectFit='cover' height={150} width={200}/>
                  </div>
                  :
                  <>
                    <FaCloudUploadAlt className={styles.icon} />
                    <span>No se ha seleccionado un archivo</span>
                  </>
                }
              </div>
              {
                firmaImage
                ?
                <button onClick={() => setFirmaImage(null)}>Remover</button>
                :
                <input id='defaultFrontalBtn' type='file' accept='image/*' onChange={frontalImageHandler} />
              }
            </div>
            <button className={styles.submitButton} onClick={() => console.log('create')}>CREAR</button>
          </form>
        </section>
      </main>
    </div>
  )
}